### ISSUE TITLE
Manuscript items cause zotsite to fail

### ISSUE THREAD

**Issue by srvanderplas** [plandes/zotsite#1]
I've replicated this issue on two different machines. With a small set of test entries in a library, zotsite works fine.

```
(base) user@Machine ~ $ zotsite export -o www/html/zotero
reading SQLite file: /home/user/Zotero/zotero.sqlite
copy: resources/site -> www/html/zotero
copy: resources/site/fonts -> www/html/zotero/fonts
copy: resources/site/img -> www/html/zotero/img
copy: resources/site/css -> www/html/zotero/css
copy: resources/site/js -> www/html/zotero/js
creating js nav tree: www/html/zotero/js/zotero-tree-data.js
copying storage /home/user/Zotero/storage -> www/html/zotero/storage
storage directory already exists--skipping: www/html/zotero/storage
```

As soon as I change the type of an entry from journal article to manuscript, zotsite fails with the following error:

```
(base) user@Machine ~ $ zotsite export -o www/html/zotero
reading SQLite file: /home/user/Zotero/zotero.sqlite
copy: resources/site -> www/html/zotero
copy: resources/site/fonts -> www/html/zotero/fonts
copy: resources/site/img -> www/html/zotero/img
copy: resources/site/css -> www/html/zotero/css
copy: resources/site/js -> www/html/zotero/js
creating js nav tree: www/html/zotero/js/zotero-tree-data.js
Traceback (most recent call last):
  File "/home/user/anaconda3/bin/zotsite", line 11, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/cli.py", line 47, in main
    cl.invoke()
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/actioncli/simple.py", line 156, in invoke
    getattr(exec_obj, meth)()
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/site.py", line 70, in export
    self._create_tree_data()
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/site.py", line 33, in _create_tree_data
    ZoteroObject.walk(lib, walker)
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/domain.py", line 38, in walk
    ZoteroObject.walk(c, walker)
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/domain.py", line 38, in walk
    ZoteroObject.walk(c, walker)
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/domain.py", line 35, in walk
    walker.enter_parent(parent)
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/nav.py", line 49, in enter_parent
    new_par = self.create_node(parent)
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/nav.py", line 30, in create_node
    icon = self.icon_name(item)
  File "/home/user/anaconda3/lib/python3.6/site-packages/zensols/zotsite/nav.py", line 22, in icon_name
    'webpage': 'bookmark'}[node.type]
KeyError: 'manuscript'

```

Deletion of the entry alone does not resolve the issue; the trash must be emptied as well. Once the trash has been emptied, zotsite works fine again.

**Comment by plandes** [comment]
This is now fixed in the [latest commit](https://github.com/plandes/zotsite/releases/tag/v0.2.0).  Try doing a
```bash
pip install -U zensols.zotsite
```
and let me know if you have any further issues.
