### ISSUE TITLE
KeyError: 'nodes'

### ISSUE THREAD

**Issue by antiracismHMSGenetics** [plandes/zotsite#10]
Hi, 

I'm super new to using git but I love you plugin so I wanted to give it a try. I installed zotsite in mac tru terminal using pip3 and tried running the following command:  zotsite export -o https://antiracismhmsgenetics.github.io/DiversityJC 

I'm getting the following error:
copying static data -> https:/antiracismhmsgenetics.github.io/DiversityJC
reading SQLite file: /Users/yasmin/Zotero/zotero.sqlite
creating js nav tree: https:/antiracismhmsgenetics.github.io/DiversityJC/js/zotero-tree-data.js
Traceback (most recent call last):
  File "/opt/anaconda3/bin/zotsite", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.7/site-packages/zensols/zotsite/cli.py", line 53, in main
    cl.invoke()
  File "/opt/anaconda3/lib/python3.7/site-packages/zensols/cli/simple.py", line 202, in invoke
    getattr(exec_obj, meth)()
  File "/opt/anaconda3/lib/python3.7/site-packages/zensols/zotsite/cli.py", line 17, in export
    self.site.export()
  File "/opt/anaconda3/lib/python3.7/site-packages/zensols/zotsite/site.py", line 162, in export
    self._create_tree_data()
  File "/opt/anaconda3/lib/python3.7/site-packages/zensols/zotsite/site.py", line 114, in _create_tree_data
    f.write(json.dumps(visitor.primary_roots, indent=2))
  File "/opt/anaconda3/lib/python3.7/site-packages/zensols/zotsite/navvisitor.py", line 52, in primary_roots
     return self.root['nodes'][0]['nodes']
KeyError: 'nodes'

Should I have installed it a different way? Thanks in advance.

**Comment by plandes** [comment]
It looks like you're using anaconda.  I'm not sure how that will work since I don't use anaconda.  I'd try uninstalling `zensols.actioncli`, `zensols.zotsite` and then install `zensols.zotsite`.  If that still doesn't work, I'd just pip install it and skip anaconda with `pip3 install zensols.zotsite`.
