### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'default_expect'

### ISSUE THREAD

**Issue by xoox** [plandes/zotsite#15]
Hi, thanks for this helpful tool. When I was doing some test with it, errors was encountered. Here is the situation.

### Reproduce

I want to try it with a fresh environment with docker.

1. `docker pull python:3`
1. `docker run -it --rm -v /home/work/Zotero:/root/Zotero python:3 bash`
1. `pip3 install zensols.zotsite`
1. `zotsite print`

The following error message was thrown.

```
Traceback (most recent call last):
  File "/usr/local/bin/zotsite", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/zensols/zotsite/cli.py", line 53, in main
    cl.invoke()
  File "/usr/local/lib/python3.9/site-packages/zensols/cli/simple.py", line 245, in invoke
    meth, exec_obj = self.create_executor(args)
  File "/usr/local/lib/python3.9/site-packages/zensols/cli/simple.py", line 233, in create_executor
    exec_obj = self.executors[exec_name](params)
  File "/usr/local/lib/python3.9/site-packages/zensols/zotsite/cli.py", line 33, in <lambda>
    'executor': lambda params: SiteCli(**params),
  File "/usr/local/lib/python3.9/site-packages/zensols/zotsite/cli.py", line 10, in __init__
    config = AppConfig.from_args(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/zensols/zotsite/config.py", line 28, in from_args
    self = cls()
  File "/usr/local/lib/python3.9/site-packages/zensols/zotsite/config.py", line 12, in __init__
    super(AppConfig, self).__init__(*args, default_expect=True, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'default_expect'
```

It seems that zotsite is out of sync with https://github.com/plandes/util . Would you please fix it?

**Comment by plandes** [comment]
@xoox Sorry you ran in to this issue.  Yes, the issue is a recent update to a dependency, and the requirements weren't clamped down for `zotsite`.  I have created a new release for which the following should reinstall and get it working:
```bash
$ pip update -U zensols.zotsite
```

**Comment by xoox** [comment]
Wow, quite impressive response time.
The updated zotsite works as expected. Thanks for your help.
