### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Cassiel-girl** [plandes/zotsite#16]
$zotsite -c /Users/xxx/Documents/zotero/zotero.sqlite  print

Traceback (most recent call last):
  File "/usr/local/bin/zotsite", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/cli.py", line 53, in main
    cl.invoke()
  File "/usr/local/lib/python3.7/site-packages/zensols/cli/simple.py", line 245, in invoke
    meth, exec_obj = self.create_executor(args)
  File "/usr/local/lib/python3.7/site-packages/zensols/cli/simple.py", line 217, in create_executor
    config = self.get_config(params)
  File "/usr/local/lib/python3.7/site-packages/zensols/cli/peraction.py", line 255, in get_config
    conf = self._create_config(conf_file)
  File "/usr/local/lib/python3.7/site-packages/zensols/cli/peraction.py", line 308, in _create_config
    isinstance(conf.parser._interpolation, ExtendedInterpolation):
  File "/usr/local/lib/python3.7/site-packages/zensols/config/iniconfig.py", line 94, in parser
    self._conf = self._create_and_load_parser()
  File "/usr/local/lib/python3.7/site-packages/zensols/config/iniconfig.py", line 80, in _create_and_load_parser
    self._read_config_content(cpath, writer)
  File "/usr/local/lib/python3.7/site-packages/zensols/config/iniconfig.py", line 62, in _read_config_content
    writer.write(f.read())
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 27: invalid start byte

**Comment by plandes** [comment]
The problem isn't with the software, it's with you giving your (binary) SQLite file as the configuration file using `-c`.  Please use `zoisite -h` and/or read the [command line help section](https://github.com/plandes/zotsite#command-line-help).
