### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by Cassiel-girl** [plandes/zotsite#18]
zotsite  print
reading SQLite file: /Users/time/Zotero/zotero.sqlite
lib (l1) (Library)
    数学 (c79,i3158) (Collection)
        微积分.pdf [document]None (i3158) (Item)
Traceback (most recent call last):
  File "/usr/local/bin/zotsite", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/cli.py", line 53, in main
    cl.invoke()
  File "/usr/local/lib/python3.7/site-packages/zensols/cli/simple.py", line 249, in invoke
    getattr(exec_obj, meth)()
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/cli.py", line 14, in print_structure
    self.site.print_structure()
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/site.py", line 93, in print_structure
    self.walker.walk(self.library, PrintVisitor(writer))
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 279, in walk
    self.walk(c, visitor)
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 279, in walk
    self.walk(c, visitor)
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 279, in walk
    self.walk(c, visitor)
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 276, in walk
    visitor.enter_parent(parent)
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 256, in enter_parent
    self.writer.write(f"{' ' * (self.depth * 4)}{str(parent)} " +
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 31, in __str__
    return '{} ({})'.format(self.__format_zobj__(), self.id)
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 150, in __format_zobj__
    abs_path = self.path
  File "/usr/local/lib/python3.7/site-packages/zensols/persist/annotation.py", line 379, in wrapped
    return pwork(*argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zensols/persist/annotation.py", line 219, in __call__
    obj = self._do_work(*argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zensols/persist/annotation.py", line 134, in _do_work
    obj = self.__do_work__(*argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zensols/persist/annotation.py", line 228, in __do_work__
    return self.worker(*argv, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/zensols/zotsite/domain.py", line 141, in path
    raise ValueError(f'unknown storage and not a file: {path}')
ValueError: unknown storage and not a file: attachments:微积分.pdf

**Comment by plandes** [comment]
I don't have any `attachments` item prefixes in my library, so I'm unsure what it is.  However, it *appears* that it acts like `storage` used to point to a file in the storage path.  Please use `pip install -U zensols.zotsite`, confirm the version as `0.3.6` with the `--version` flag and try it again.  Released as [31c036d](https://github.com/plandes/zotsite/commit/48704eda8106185c130a4c580cf329f31aea8cc7).
