### ISSUE TITLE
Keyerror: 'nodes'

### ISSUE THREAD

**Issue by michael1maass** [plandes/zotsite#20]
Hi, 
after figuring out, that --datadir is not parsed (its not in the Helpfile so why should it) and I got everything to rund with the Config file, I am now stopped at the above error, which I cannot cure. 

I updated the Zenols.actioncli an zenols.zotsite to current versions allready 

`
c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Scripts>zotsite export -o c:/LaufwerkU/Sites/Zotero -c c:/laufwerkU/scripte/zotsite.cnf
copying static data -> c:\LaufwerkU\Sites\Zotero
reading SQLite file: c:\LaufwerkU\Zotero\zotero.sqlite
creating js nav tree: c:\LaufwerkU\Sites\Zotero\js\zotero-tree-data.js
Traceback (most recent call last):
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "c:\Program Files (x86)\Microsoft Visual Studio\Shared\Python39_64\Scripts\zotsite.exe\__main__.py", line 7, in <module>
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\site-packages\zensols\zotsite\cli.py", line 53, in main
    cl.invoke()
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\site-packages\zensols\cli\simple.py", line 251, in invoke
    getattr(exec_obj, meth)()
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\site-packages\zensols\zotsite\cli.py", line 17, in export
    self.site.export()
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\site-packages\zensols\zotsite\site.py", line 171, in export
    self._create_tree_data()
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\site-packages\zensols\zotsite\site.py", line 123, in _create_tree_data
    f.write(json.dumps(visitor.primary_roots, indent=2))
  File "c:\program files (x86)\microsoft visual studio\shared\python39_64\lib\site-packages\zensols\zotsite\navvisitor.py", line 52, in primary_roots
    return self.root['nodes'][0]['nodes']
KeyError: 'nodes'
`

**Comment by plandes** [comment]
I should not be using `zensols.actioncli`, the new version uses `zensols.util` (see the [requirements file](https://github.com/plandes/zotsite/blob/master/src/python/requirements.txt)).  You can do a `make deps` if you have GNU make installed.  However, this looks like windows, so you might want to do a `pip install -r src/python/requirements.txt` instead.

Let me know how this goes.

**Comment by GioFic95** [comment]
Hi,
I found out that the error in object is due to the fact that, at least on Windows, [this line](https://github.com/plandes/zotsite/blob/master/src/python/zensols/zotsite/db.py#L41)
```sql
select c.collectionId c_id, ci.itemId c_iid,
        c.parentCollectionId c_pid, c.collectionName c_name
    from collections c
    left join collectionItems ci on c.collectionId = ci.collectionId
    where c.libraryId = %(library_id)s and   --                                  this one
          c.collectionName like '%(coll_name)s'
```
forces to look for libraries with a fixed ID, which is 1 by default ([config](https://github.com/plandes/zotsite/blob/master/src/python/zensols/zotsite/config.py#L31)).

This is fine for the personal library, but not for group libraries.
I modified the aforementioned query
```sql
select c.libraryId c_lid, c.collectionId c_id, ci.itemId c_iid,
```
and added a print [here](https://github.com/plandes/zotsite/blob/master/src/python/zensols/zotsite/db.py#L174) to show the IDs of my libraries:
```python
for row in conn.execute(self._collection_sql(wparams)):
    print("row:", row)
```
which are 1 for my personal library and 2 for a shared group library:
```bash
row: {'c_lid': 1, 'c_id': 15, 'c_iid': 3291, 'c_pid': None, 'c_name': 'aaa'}
row: {'c_lid': 2, 'c_id': 14, 'c_iid': 2139, 'c_pid': None, 'c_name': 'bbb'}
```

So, maybe you might expose this behavior in the docs, but it is not so easy to find the library IDs, or remove the first `where` clause in the query above to include all the libraries, or at least change the default behavior.

It also seems that the second `where` clause in the query above is ignored, since `name_pat`, which becomes `coll_name` in `wparams` [here](https://github.com/plandes/zotsite/blob/master/src/python/zensols/zotsite/db.py#L171), always gets its default value `'%'` defined [here](https://github.com/plandes/zotsite/blob/master/src/python/zensols/zotsite/db.py#L19), since the `DatabaseReader` is called without specifying the relative parameter by the `SiteCreator` [here]:(https://github.com/plandes/zotsite/blob/master/src/python/zensols/zotsite/site.py#L35)
```python
self.db = DatabaseReader(config.data_dir, library_id=cnf.library_id)
```
and the collection are filtered only later by the `PruneVisitor`. So maybe the query can be simplified by removing both of the `where` clauses.

Please let me know if it's useful and if I can help.
Thanks,
Giovanni

**Comment by plandes** [comment]
Thanks for all of this.  It looks like the `name_pat` configuration option was used for both prune and in the DB where clause.  You're right that the configuration wasn't being used.

Regarding using this on Windows: no that shouldn't be a problem as only `pathlib.Path` is used throughout the code, which *should* deal with Windows paths natively.

I have done a major upgrade to the code base, which includes better documentation and a separation of these values.  Take a look at the docs, and specifically the `prune_pattern`, and what you're looking for: `collection_like`.  The `library_id` should have already worked.

The bug you mentioned has also been fixed.

Please use `pip install -U sensors.zotsite` and try again.  Please let me know either way if it works for you.

**Comment by GioFic95** [comment]
Hi @plandes ,
thank you very much for the updates and sorry for the late response.

I updated the library as you suggested, now it seems that i cannot run
```
zotsite print
```
since i get the error
```
zotsite: error: missing option --config
```
But, if I provide a config file, then I get
```
configparser.InterpolationMissingOptionError: Bad value substitution: option 'data_dir' in section 'default' contains an interpolation key 'env:home' which is not a valid option name. Raw value: '${env:home}/Zotero'

...

zensols.config.configbase.ConfigurableError: Could not populate <ImportIniConfig(f=zotsite\resources\default.conf){default}>:[default]: Bad value substitution: option 'data_dir' in section 'default' contains an interpolation key 'env:home' which is not a valid option name. Raw value: '${env:home}/Zotero' in file C:\Users\super\Desktop\tmp\zotsite.config
```
where `C:\Users\super\Desktop\tmp\zotsite.config` is my config file.

I tried replacing
```
data_dir = ${env:home}/Zotero
```
with
```
data_dir = ~/Zotero
```
in [`default.conf`](https://github.com/plandes/zotsite/blob/master/resources/default.conf#L3) and now it can use my config file.

I can see the updated error message
```
zotsite: error: no collections found; maybe too restrictive collections regular expression?
```
which is way clearer than the previous one (`Keyerror: 'nodes'`), even if in my case the issue is with libraries rather than collections.

By the way, I cannot find any detail about the `library_id` in the [docs](https://github.com/plandes/zotsite/blob/master/doc/usage.md). Are you talking about other docs?

Thank you very much again

**Comment by plandes** [comment]
Hi @GioFic95 

Sorry you had to do all that.  I have put out a new release that defaults the home directory using the tilde and makes the configuration file optional.

Regarding the home directory: I don't have a Windows machine to test this on, so your feedback and test results are the only way I know how to make these changes.

Regarding the error message: you may be right about the terminology of collections vs library from a user point of view.  But the program only understands things using the Zotero code and DB parlance, which uses the term *collections*.  I have never dealt with collections queried from personal libraries, so I might be missing something here as I have never used them.

Regarding the documentation on the `library_id`--what we've discussed in this thread is all I know as once again I have no experience with them (note that I did update the usage documentation with this value).  However, from what I've seen, adding the `library_id` entry in the configuration file you created with your personal library should work.

If it doesn't let me know and I might be able to find something online that enables the application to use personal libraries.  Again, from what I've read, that term used in the SQL select is all that should need to change

**Comment by plandes** [comment]
@GioFic95,

Glad to hear you got everything working.

Your ideas on the documentation sound good, but ATM I have little time to continue working on this.  Would you mind editing the documentation as a pull request?  if you do, I will merge it after any of my own minor edits, if necessary.
