### ISSUE TITLE
error pointing towards inexisting folder when exporting collection with REGEX-option

### ISSUE THREAD

**Issue by floriandierickx** [plandes/zotsite#26]
Situation: I have a collection (which in itself is a 'sub-collection') called 'CC Impacts' with several sub-folders inside:
![image](https://github.com/plandes/zotsite/assets/12695083/89b74d12-ef44-45f7-baa1-284433fac6c3)

When I run the command
```
zotsite export --collection ".*CC\s*Impacts.*" 
```
(1) the website is created in the root folder (which by the way looks and works great!), which includes the folder 'CC Impacts', all the sub-folders and all references.
![image](https://github.com/plandes/zotsite/assets/12695083/f98fea70-d90e-4963-98c5-62c2ee832b22)

but there seems to be an issue when the script looks for attachments as (2) following error appears (full output of command line):
```
zotsite: exporting site: None
zotsite: copying static data -> zotero-site
zotsite: creating js nav tree: zotero-site\js\zotero-tree-data.js
zotsite: reading SQLite file: C:\Users\USER\Zotero\zotero.sqlite
zotsite: no such icon found for dataset
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: creating js metadata: zotero-site\js\zotero-meta.js
zotsite: copying storage to zotero-site
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Scripts\zotsite.exe\__main__.py", line 7, in <module>
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\cli.py", line 20, in main
    harness.invoke(args, **kwargs)
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\harness.py", line 347, in invoke
    return cli.invoke(args[1:])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 758, in invoke
    return self._handle_error(e)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 735, in _handle_error
    raise ex
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 754, in invoke
    app_res: ApplicationResult = app.invoke()
                                 ^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 409, in invoke
    res: Any = invokable()
               ^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 230, in __call__
    return self.method(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\app.py", line 57, in export
    self.site_creator.export()
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\screate.py", line 192, in export
    self._copy_storage()
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\screate.py", line 153, in _copy_storage
    self.walker.walk(self.library, fsvisitor)
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 306, in walk
    self.walk(c, visitor)
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 306, in walk
    self.walk(c, visitor)
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 306, in walk
    self.walk(c, visitor)
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 305, in walk
    visitor.visit_child(c)
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\fscpvisitor.py", line 53, in visit_child
    shutil.copyfile(src, dst)
  File "C:\Users\USER\AppData\Local\anaconda3\envs\zotsite\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Zotero\\storage\\9QFSS3TC\\false'
```

The folder `C:\Users\dxf\Zotero\storage\9QFSS3TC\` does not exist (but the `storage` folder is the correct destination for Zotero-items).

When I run the debug mode (`zotsite export --collection ".*CC\s*Impacts.*" --level debug`), the full output is too large for my powershell to contain, but in the end it looks like the script is looking for an item named `false` in this inexisting folder (although I would expect a file-name as in the preceding example) :
```
zotsite: child: C:\Users\USER\Zotero\storage\9AYV8DDI\2017 - Iyer et al - Measuring progress from nationally determined contributions to mid-century.pdf
zotsite: copy: C:\Users\USER\Zotero\storage\9AYV8DDI\2017 - Iyer et al - Measuring progress from nationally determined contributions to mid-century.pdf -> zotero-site\storage\i25315.pdf
zotsite: child: None
zotsite: child: C:\Users\USER\Zotero\storage\9QFSS3TC\false
zotsite: copy: C:\Users\USER\Zotero\storage\9QFSS3TC\false -> zotero-site\storage\i26558
zotsite: shcopy: C:\Users\USER\Zotero\storage\9QFSS3TC\false -> zotero-site\storage\i26558
Traceback (most recent call last):
# same output as output without --level debug
```

To find this (seemingly inexisting?) reference in the SQlite-database, I used [DB Browser for SQLite](https://sqlitebrowser.org/).

I am not familiar with the Zotero SQLite database-structure, but from the `item`-table it appears that the `key` `9QFSS3TC` corresponds to `itemID` `26558`, proving its existence:
![image](https://github.com/plandes/zotsite/assets/12695083/21521858-f3b3-47a4-92ee-275b1e39cc8e)

In another table `itemAttachments` the `itemID` `26558` indicates that the storage location of this item is defined as `storage:false`.
![image](https://github.com/plandes/zotsite/assets/12695083/be0f37e7-3eca-4619-878e-7e6e6f5c2263)

This seems to be the culprit. I don't know whether this is native Zotero-behaviour or because of an add-on, but multiple items do have the value `storage:false` under `path` here.

In the table `itemCreators` it appears there is no author associated with the item. 

In the table `itemData` there are three `valueID`s associated with the item
![image](https://github.com/plandes/zotsite/assets/12695083/694be26d-e024-4184-8807-90dd4a87022e)

In the table `itemDataValues` those three `valueID`s point towards:
| valueID | value                                                                                                      |
|---------|------------------------------------------------------------------------------------------------------------|
| 79617   | 2018 - papalexiou et al - global, regional, and megacity trends in the highest temperature of the year.pdf |
| 79618   | http://onlinelibrary.wiley.com/doi/10.1002/2017EF000709/pdf                                                |
| 79619   | 2018-01-24 14:33:53                                                                                        |

The item itself look like any other item in Zotero, but the file is just only stored online (and not synced locally). This probably explains the value `storage:false` ?

Or maybe the problem is that Zotero did not yet create a folder associated with this item (because it's only online), and normally it should have created one?

Now I'm wondering: does this error cause the chain of parsing attachments to break, or did the code skip just only this erroneous file and proceed to the other files?

**Comment by floriandierickx** [comment]
Hehe, that's a good strategy :) Indeed, it's a Zotero-related issue.

I installed the new release with `pip install zensols.zotsite==0.8.1` which installed succesfully:

```
Collecting zensols.zotsite==0.8.1
  Obtaining dependency information for zensols.zotsite==0.8.1 from https://files.pythonhosted.org/packages/ca/be/d602319ee234e8337f7c48323b60d77a9178c2e490e27f0f4d69fa51e92b/zensols.zotsite-0.8.1-py3-none-any.whl.metadata
  Downloading zensols.zotsite-0.8.1-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: zensols.util~=1.13.0 in c:\users\dxf\appdata\local\anaconda3\envs\zotsite\lib\site-packages (from zensols.zotsite==0.8.1) (1.13.0)
Requirement already satisfied: configparser~=5.2.0 in c:\users\dxf\appdata\local\anaconda3\envs\zotsite\lib\site-packages (from zensols.util~=1.13.0->zensols.zotsite==0.8.1) (5.2.0)
Requirement already satisfied: PyYAML>=5.4 in c:\users\dxf\appdata\local\anaconda3\envs\zotsite\lib\site-packages (from zensols.util~=1.13.0->zensols.zotsite==0.8.1) (6.0.1)
Requirement already satisfied: parse>=1.9.0 in c:\users\dxf\appdata\local\anaconda3\envs\zotsite\lib\site-packages (from zensols.util~=1.13.0->zensols.zotsite==0.8.1) (1.19.1)
Requirement already satisfied: frozendict in c:\users\dxf\appdata\local\anaconda3\envs\zotsite\lib\site-packages (from zensols.util~=1.13.0->zensols.zotsite==0.8.1) (2.3.8)
Downloading zensols.zotsite-0.8.1-py3-none-any.whl (625 kB)
   ---------------------------------------- 625.4/625.4 kB 79.5 kB/s eta 0:00:00
Installing collected packages: zensols.zotsite
  Attempting uninstall: zensols.zotsite
    Found existing installation: zensols.zotsite 0.8.0
    Uninstalling zensols.zotsite-0.8.0:
      Successfully uninstalled zensols.zotsite-0.8.0
Successfully installed zensols.zotsite-0.8.1
```

and did run again the code `zotsite export --collection ".*CC\s*Impacts.*"`.

It seems the code is still very eager to find the missing link :p :

```
zotsite: exporting site: None
zotsite: copying static data -> zotero-site
zotsite: creating js nav tree: zotero-site\js\zotero-tree-data.js
zotsite: reading SQLite file: C:\Users\dxf\Zotero\zotero.sqlite
zotsite: no such icon found for dataset
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: creating js metadata: zotero-site\js\zotero-meta.js
zotsite: copying storage to zotero-site
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Scripts\zotsite.exe\__main__.py", line 7, in <module>
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\cli.py", line 20, in main
    harness.invoke(args, **kwargs)
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\harness.py", line 347, in invoke
    return cli.invoke(args[1:])
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 758, in invoke
    return self._handle_error(e)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 735, in _handle_error
    raise ex
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 754, in invoke
    app_res: ApplicationResult = app.invoke()
                                 ^^^^^^^^^^^^
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 409, in invoke
    res: Any = invokable()
               ^^^^^^^^^^^
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\cli\app.py", line 230, in __call__
    return self.method(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\app.py", line 57, in export
    self.site_creator.export()
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\screate.py", line 196, in export
    self._copy_storage()
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\screate.py", line 157, in _copy_storage
    self.walker.walk(self.library, fsvisitor)
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 306, in walk
    self.walk(c, visitor)
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 306, in walk
    self.walk(c, visitor)
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 306, in walk
    self.walk(c, visitor)
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\domain.py", line 305, in walk
    visitor.visit_child(c)
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\fscpvisitor.py", line 68, in visit_child
    raise e
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\site-packages\zensols\zotsite\fscpvisitor.py", line 62, in visit_child
    shutil.copyfile(src, dst)
  File "C:\Users\dxf\AppData\Local\anaconda3\envs\zotsite\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\dxf\\Zotero\\storage\\9QFSS3TC\\false'
```

**Comment by floriandierickx** [comment]
Yes sorry, I wanted to be too fast, never a good idea :)

I took the configuration file content from https://github.com/plandes/zotsite/blob/master/test-resources/zotsite.conf and uncommented the robust_fs-option:

```
#-*-conf-*-

[default]
# the directory where the Zotero DB files live
data_dir = ~/Zotero
# the library used to generate the site, which defaults to the Personal
library_id = 1
# when using --collection, match on items as well
match_children = True
# whether to use unique item IDs for the file names or the full PDF file name;
# either: ``item`` or ``long``
file_mapping = item
# how to generate unique identifiers for URLS; either ``none``, or
# ``betterbib``
id_mapping = betterbib
# whether or not to sort items; either: ``none`` or ``case`` (non-case might be
# added later)
sort = none
# used to select collections from the SQLite database (percent signs are
# escaped with a double percent sign)
collection_like = %%
# a regular expression used to filter collection nodes
prune_pattern = None
# the default output directory to store the collection
out_dir = None

## if the below is uncommented, it will continue to try to export the even when
## encountering file system copy issues.
[site_creator]
robust_fs = True
```

Then I ran the command with the --config option indicating the changed config-file.

Result: funnily there are less errors indicated as compared to the standard (uncommented) config-file:

```
(zotsite) PS C:\Users\USER\Documents\Data\Zotsite-climate-impacts> zotsite export --collection ".*CC\s*Impacts.*" --config "C:\[folders]\zotsite.conf"
zotsite: exporting site: None
zotsite: copying static data -> None
zotsite: creating js nav tree: None\js\zotero-tree-data.js
zotsite: reading SQLite file: C:\Users\USER\Zotero\zotero.sqlite
zotsite: reading bibtex DB at C:\Users\USER\Zotero\better-bibtex.sqlite
zotsite: no such icon found for dataset
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: no such icon found for document
zotsite: creating js metadata: None\js\zotero-meta.js
zotsite: copying storage to None
zotsite: could not copy C:\Users\USER\Zotero\storage\9QFSS3TC\false to None\storage\i26558: [Errno 2] No such file or directory: 'C:\\Users\\USER\\Zotero\\storage\\9QFSS3TC\\false'
```
I check the size of the storage-folders with and without uncommenting the option in the config-file, and the size of the storage without `robust_fs = True` is almost half the size of the storage folder with the option active.

Conclusion: it works! Thank you so much!!
